<?php use \Phalcon\Tag as Tag; ?>
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <h1 class="header center white-text lighten-1 accent-3">WebBook Generator</h1>
        <div class="row center">
            <h5 class="header col s12 light white-text">Modernes Tool zum Konvertieren einer Pdf in ein WebBook</h5>
        </div>
        
        <div class="row center">
            <?=Tag::linkTo(array("user/new", "Starten!", "class" => "btn-large waves-effect waves-light light-blue lighten-1 black-text"));?>
        </div>
    </div>
</div>
<div class="container" id="threeCols">
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text headingSection"><i class="mdi-image-flash-on"></i></h2>
                    <h5 class="center white-text">Schneller Weg</h5>

                    <p class="light white-text">Mit unserem WebBook-Generator haben Sie die Möglichkeit Ihre Pdf's schnell in webbasierte WebBooks zu konvertieren. Erstellte WebBooks können Sie in allen Ihren Projekten einsetzen. Eine stapelweise Bearbeitung der Pfd's ist ebenfalls möglich.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text headingSection"><i class="mdi-social-group"></i></h2>
                    <h5 class="center white-text">Service und Updates</h5>

                    <p class="light white-text">Für uns ist es wichtig Sie jederzeit zu unterstützen. Daher haben wir zum Einen den Bereich "Service". Dort finden Sie eventuell Antworten auf häufige Fragen rund um die Erstellung und Nutzung von Ihren WebBooks. Sollten Sie dort keine passende Antwort finden, haben Sie die Möglichkeit über Ihr Account direkten Kontakt mit uns aufzunehmen.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center light-blue-text headingSection"><i class="mdi-action-settings"></i></h2>
                    <h5 class="center white-text">Leicht im Einsatz</h5>

                    <p class="light white-text">Bei Entwicklung dieses Tools haben wir unser Augenmerk auf die angenehme Nutzung des Services und einfach Bedingung der Prozesse gelegt. Alle Funktionen sind auf das Wesentliche komprimiert. Somit kommen Sie schnell zum Ziel und können das WebBook nach wenigen Klicks einsetzen.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col m12">
            <h3 class="white-text center-align shadowHeader">In wenigen Schritten mit unserem Tool zu Ihrem WebBook!</h3>
        </div>
    </div>
</div>
<div class="container" id="fourCols">
    <div class="row">
        <div class="col s12 m3">
            <div class="row">
                <p class="checkpoint center-align white-text"><span>1</span></p>
            </div>
            <div class="row">
                <h5 class="light-blue-text center-align checkpointheader">Registrierung</h5>
                <p class="white-text center-align">Schnell und unkopliziert ein Benutzerkonto erstellen.</p>
            </div>
        </div>
        <div class="col s12 m3">
            <div class="row">
                <p class="checkpoint center-align white-text"><span>2</span></p>
            </div>
            <div class="row">
                <h5 class="light-blue-text center-align checkpointheader">Pdf hochladen</h5>
                <p class="white-text center-align">Laden Sie Ihre Pdfs hoch, die Sie in WebBooks umwandeln möchten.</p>
            </div>
        </div>
        <div class="col s12 m3">
            <div class="row">
                <p class="checkpoint center-align white-text"><span>3</span></p>
            </div>
            <div class="row">
                <h5 class="light-blue-text center-align checkpointheader">WebBook generieren</h5>
                <p class="white-text center-align">Starten Sie die Generierung von WebBooks mit wenigen Klicks.</p>
            </div>
        </div>
        <div class="col s12 m3">
            <div class="row">
                <p class="checkpoint center-align white-text"><span>4</span></p>
            </div>
            <div class="row">
                <h5 class="light-blue-text center-align checkpointheader">WebBooks nutzen</h5>
                <p class="white-text center-align">Nutzen Sie Ihre WebBooks in Ihren Online-Projekten oder Ihren Webseiten.</p>
            </div>
        </div>
    </div>
</div>