<?php
use Phalcon\Mvc\Url;
use \Phalcon\Tag as Tag;
$url = new Url();
?>
<div class="section">
	<div class="container">
	    <div class="row">
	        <div class="l12 s12">
	            <h1 class="header center white-text lighten-1 accent-3">Benutzer Verwaltung</h1>
	        </div>
	    </div>
	</div>
</div>
<div class="divider"></div>
<div class="section">
  <div class="container">
    <div class="row marginNull">
      <div class="col s12 m12 l6">
          <?=Tag::linkTo(array("/admincenter", 'Zum Admin-Center<i class="material-icons left">home</i>', 'class' => 'btn waves-effect waves-light fullsize light-blue lighten-1'));?>
      </div>
      <div class="col s12 m12 l6">
		<a class="btn waves-effect waves-light fullsize light-blue lighten-1 modal-trigger" href="#addpro">
			Benutzer hinzufügen<i class="material-icons right">person_add</i>
		</a>
		<div id="addpro" class="modal">
			<div class="modal-content">
				<div class="row">
					<h4 class="center">Benutzer hinzufügen</h4>
				</div>
				<div class="row">
					<div class="col s12 m12 l6">
						<?=Tag::linkTo(array("/adminuser/adduser", 'Kunde hinzufügen<i class="material-icons black-text right">person_add</i>', 'class' => 'btn waves-effect waves-light fullsize teal accent-3 black-text'));?>
					</div>
					<div class="col s12 m12 l6">
						<?=Tag::linkTo(array("/adminuser/addadmin", 'Administrator hinzufügen<i class="material-icons black-text right">person_add</i>', 'class' => 'btn waves-effect waves-light fullsize teal accent-3 black-text'));?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col s12 m12 l12">
					<a class="btn waves-effect fullsize light-blue lighten-1 modal-action modal-close waves-light" href="#!">Schließen <i class="material-icons left">arrow_back</i></a>
				</div>
			</div>
		</div>
      </div>
    </div>
  </div>
</div>
<div class="divider"></div>
<div class="section">
	<div class="container tabBlue">
		<div class="row">
			<div class="col s12 m12 l12">
				<ul class="tabs">
					<li class="tab col s6 m6 l6">
						<a href="#usercm">Kunden</a>
					</li>
					<li class="tab col s6 m6 l6">
						<a href="#userad">Administratoren</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div id="usercm" class="col s12">
		<div class="section">
			<div class="container">
				<div class="row">
					<h5 class="white-text center">Kunden - Liste</h5>
				</div>
				<div class="row">
					<?php $ccounter = 1; ?>
					<ul class="collapsible popout" data-collapsible="accordion" id="customerlist">
						<?php foreach($customers as $c) : ?>
							<?php $account = Account::getCustomerAccount($c->id); ?>
							<?php $lands = Land::getAll(); ?>
							<li>
								<div class="collapsible-header">
									<?php if($account->active == 1) : ?>
											<?php if($c->company != '---') : ?>
												<i class="material-icons teal-text text-accent-3">location_city</i>
											<?php else : ?>
												<i class="material-icons teal-text text-accent-3">account_circle</i>
											<?php endif; ?>
									<?php else : ?>
											<?php if($c->company != '---') : ?>
												<i class="material-icons pink-text text-lighten-1">location_city</i>
											<?php else : ?>
												<i class="material-icons pink-text text-lighten-1">account_circle</i>
											<?php endif; ?>
									<?php endif; ?>
									<span class="right"><?php echo $c->company != '---' ? '<strong>Firma/Organisation:</strong> '.$c->company : '<strong>Name:</strong> '.$c->firstname.' '.$c->lastname; ?></span>
								</div>
								<div class="collapsible-body white">
									<div class="container">
										<div class="row">
											<table class="bordered responsive-table">
												<tr>
													<td class="black-text">
														<strong>Vorname:</strong>
													</td>
													<td class="black-text">
														<?=$c->firstname;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>Nachname:</strong>
													</td>
													<td class="black-text">
														<?=$c->lastname;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>E-Mail:</strong>
													</td>
													<td class="black-text">
														<?=$c->email;?>
													</td>
												</tr>
												<?php if($c->company != '---') : ?>
													<tr>
														<td class="black-text">
															<strong>Firma/Organisation:</strong>
														</td>
														<td class="black-text">
															<?=$c->company;?>
														</td>
													</tr>
												<?php endif; ?>
												<?php if($c->phone != '---') : ?>
													<tr>
														<td class="black-text">
															<strong>Telefon:</strong>
														</td>
														<td class="black-text">
															<?=$c->phone;?>
														</td>
													</tr>
												<?php endif; ?>
												<tr>
													<td class="black-text">
														<strong>Straße:</strong>
													</td>
													<td class="black-text">
														<?=$c->street;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>PLZ:</strong>
													</td>
													<td class="black-text">
														<?=$c->zip;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>Stadt:</strong>
													</td>
													<td class="black-text">
														<?=$c->city;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>Land:</strong>
													</td>
													<td class="black-text">
														<?php echo Land::getLand($c->land)->title; ?>
													</td>
												</tr>
											</table>
										</div>
										<div class="row">
											<div class="col s12 m12 l6">
												<a class="btn waves-effect waves-light fullsize light-blue lighten-1 modal-trigger" href="#accinfo<?php echo $account->id; ?>">
		                                            Account-Info<i class="material-icons left">info</i>
		                                        </a>
												<div id="accinfo<?php echo $account->id; ?>" class="modal">
		                                        <div class="modal-content">
		                                          <h4>Account-Info von: <strong><?php echo $c->company != '---' ? $c->company : $c->firstname.' '.$c->lastname; ?></strong></h4>
		                                            <div class="row">
		                                                <table class="bordered responsive-table">
															<tr>
																<td class="black-text">
																	<strong>Account-Status:</strong>
																</td>
																<td class="black-text">
																	<?php if($account->active == 1) : ?>
																		<span class="teal-text text-accent-3">Aktiv</span>
																	<?php else : ?>
																		<span class="pink-text text-lighten-1">inaktiv</span>
																	<?php endif; ?>
																</td>
															</tr>
															<tr>
																<td class="black-text">
																	<strong>Account-Key:</strong>
																</td>
																<td class="black-text">
																	<?=$account->akey;?>
																</td>
															</tr>
		                                                    <tr>
		                                                        <td class="black-text">
		                                                            <strong>Tarif:</strong>
		                                                        </td>
		                                                        <td class="black-text">
		                                                            <?php echo Tariff::getTariff($account->tariff_id)->title; ?>
		                                                        </td>
		                                                    </tr>
		                                                    <?php if($account->active == 1) :?>
																<tr>
																	<td class="black-text">
																		<strong>Aktiv sein:</strong>
																	</td>
																	<td class="black-text">
																		<?php echo date('d.m.Y', strtotime($account->active_from)); ?>
																	</td>
																</tr>
																<tr>
																	<td class="black-text">
																		<strong>Aktiv bis:</strong>
																	</td>
																	<td class="black-text">
																		<?php echo date('d.m.Y', strtotime($account->active_untill)); ?>
																	</td>
																</tr>
															<?php endif; ?>
															<tr>
																<td class="black-text">
																	<strong>Vertragslaufzeit:</strong>
																</td>
																<td>
																	<?php echo Tariff::getTariff($account->tariff_id)->activeperiodemonth.' Monate'; ?>
																</td>
															</tr>
		                                                </table>
		                                            </div>
		                                        </div>
												<div class="modal-footer">
		                                                <div class="col s12 m12 l6">
		                                                    <a class="btn waves-effect fullsize light-blue lighten-1 modal-action modal-close waves-light" href="#!">Schließen <i class="material-icons left">arrow_back</i></a>
		                                                </div>
														<div class="col s12 m12 l6">
															<?php if($account->active == 0) : ?>
					                                            <a class="btn black-text waves-effect waves-light fullsize teal accent-3" href="<?php echo $url->get("adminaccount/activate/".$account->id."/adminuser") ?>">
					                        			            Aktivieren<i class="material-icons right">power_settings_new</i>
					                        			        </a>
					                                        <?php else : ?>
					                                            <a class="btn waves-effect waves-light fullsize pink lighten-1" href="<?php echo $url->get("adminaccount/deactivate/".$account->id."/adminuser") ?>">
					                        			            Deaktivieren<i class="material-icons right">power_settings_new</i>
					                        			        </a>
					                                        <?php endif; ?>
														</div>
		                                        </div>
		                                      </div>
											</div>
											<div class="col s12 m12 l6">
												<a class="btn waves-effect fullsize light-blue lighten-1 modal-trigger waves-light" href="#mailto<?=$c->id;?>">E-Mail an Kunde <i class="material-icons right">email</i></i></a>
												<div id="mailto<?=$c->id;?>" class="modal modal-fixed-footer">
			                                        <div class="modal-content">
			                                          <h4>Bearbeiten von: <strong><?php echo $c->company != '---' ? $c->company : $c->firstname.' '.$c->lastname; ?></strong></h4>
			                                            <div class="row">
															<form action="adminuser/update/<?=$c->id;?>/adminuser" method="post">
																<div class="input-field col s12 m12 l12 black-text">
																		<input id="firstname" name="firstname" type="text" value="<?=$c->firstname;?>" class="validate" />
																		<label for="firstname">Vorname:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text">
																	<input type="text" name="lastname" value="<?=$c->lastname;?>" class="validate">
																	<label for="lastname">Nachname:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text">
																	<input type="text" name="email" value="<?=$c->email;?>" class="validate">
																	<label for="email">Email:</label>
																</div>
																<?php if($c->company != '---') : ?>
																	<div class="input-field col s12 m12 l12 black-text">
																		<input type="text" name="company" value="<?=$c->company;?>" class="validate">
																		<label for="company">Firma/Organisation:</label>
																	</div>
																<?php endif; ?>
																<?php if($c->phone != '---') : ?>
																	<div class="input-field col s12 m12 l12 black-text">
																		<input type="text" name="phone" value="<?=$c->phone;?>" class="validate">
																		<label for="phone">Telefon:</label>
																	</div>
																<?php endif; ?>
																<div class="input-field col s12 m12 l12 black-text">
																	<input type="text" name="street" value="<?=$c->street;?>" class="validate">
																	<label for="street">Straße:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text" class="validate">
																	<input type="text" name="zip" value="<?=$c->zip;?>">
																	<label for="zip">PLZ:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text" class="validate">
																	<input type="text" name="city" value="<?=$c->city;?>">
																	<label for="city">Stadt:</label>
																</div>
																<div class="input-field col s12 l12 m12 black-text">
														            <select name="land" id="land">
																		<option value="<?php echo Land::getLand($c->land)->id; ?>" selected><?php echo Land::getLand($c->land)->title; ?>
																		<?php foreach ($lands as $l) : ?>
														                    <option value="<?=$l->id;?>"><?=$l->title;?></option>
														                <?php endforeach; ?>
														            </select>
														            <label for="project">Projekt Auswahl: bitte wählen Sie ein Projekt aus.</label>
														        </div>
			                                            </div>
			                                        </div>
													<div class="modal-footer">
															<div class="col s12 m12 l6">
																<a class="btn waves-effect fullsize light-blue lighten-1 modal-action modal-close waves-light" href="#!">Schließen <i class="material-icons left">arrow_back</i></a>
															</div>
															<div class="col s12 m12 l6">
																<button class="btn waves-effect waves-light fullsize teal accent-3 black-text" type="submit" id="createDirect" name="action" value="updatecustomer">Speichern
																		<i class="material-icons right black-text">done</i>
																</button>
																</form>
															</div>
													</div>
		                                      </div>
											</div>
										</div>
										<div class="row">
											<div class="col s12 m12 l6">
												<a class="btn waves-effect fullsize light-blue lighten-1 modal-trigger waves-light" href="#mailto<?=$c->id;?>">Bearbeiten <i class="material-icons left">edit</i></i></a>
											</div>
											<?php if($account->active == 1) : ?>
		                                        <div class="col s12 m12 l6">
		                                            <a class="btn waves-effect fullsize light-blue disabled tooltipped lighten-1 waves-light" data-position="top" data-delay="10" data-tooltip="Account muss zuerst deaktiviert werden." href="#!">Löschen <i class="material-icons right">delete</i></i></a>
		                                        </div>
		                                    <?php else : ?>
		                                        <div class="col s12 m12 l6">
		                                            <a class="btn waves-effect fullsize pink lighten-1 modal-trigger waves-light" href="#delcs<?=$c->id;?>">Löschen <i class="material-icons right">delete</i></i></a>
		                                            <div id="delcs<?php echo $c->id; ?>" class="modal">
		                                            <div class="modal-content">
		                                              <h4>Löschen von: <strong><?php echo $c->firstname.' '.$c->lastname; ?></strong></h4>
		                                                <div class="row">
															<p class="pink-text text-lighten-1">Achtung! Es werden alle zugehörigen Daten inkl. aller Webbooks gelöscht. Wenn Sie sich sicher sind, dann klicken Sie auf <strong>"Löschen bestätigen"</strong>.</p>
		                                                </div>

		                                            <div class="modal-footer">
		                                                <div class="row">
		                                                    <div class="col s12 m12 l6">
		                                                        <a class="btn waves-effect fullsize light-blue lighten-1 modal-action modal-close waves-light" href="#!">Schließen <i class="material-icons left">arrow_back</i></a>
		                                                    </div>
		                                                    <div class="col s12 m12 l6">
		                                                        <a class="btn waves-effect waves-light fullsize pink lighten-1" href="<?php echo $url->get("adminuser/delete/".$c->id."/adminuser") ?>">
		                                    			            Löschen bestätigen<i class="material-icons right">delete</i>
		                                    			        </a>
		                                                    </div>
		                                                </div>
		                                            </div>
		                                            </div>
		                                          </div>
		                                        </div>
		                                    <?php endif; ?>
										</div>
									</div>
								</div>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
    <div id="userad" class="col s12">
		<div class="section">
			<div class="container">
				<div class="row">
					<h5 class="white-text center">Administratoren - Liste</h5>
				</div>
				<div class="row">
					<?php $ccounter = 1; ?>
					<ul class="collapsible popout" data-collapsible="accordion" id="customerlist">
						<?php foreach($admins as $a) : ?>
							<li>
								<div class="collapsible-header">
									<i class="material-icons">account_circle</i>
									<span class="right"><strong>Name:</strong> <?php echo $a->firstname.' '.$a->lastname; ?></span>
								</div>
								<div class="collapsible-body white">
									<div class="container">
										<div class="row">
											<table class="bordered">
												<tr>
													<td class="black-text">
														<strong>Vorname:</strong>
													</td>
													<td class="black-text">
														<?=$a->firstname;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>Nachname:</strong>
													</td>
													<td class="black-text">
														<?=$a->lastname;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>E-Mail:</strong>
													</td>
													<td class="black-text">
														<?=$a->email;?>
													</td>
												</tr>
												<tr>
													<td class="black-text">
														<strong>Erstellt am:</strong>
													</td>
													<td class="black-text">
														<?php echo date('d.m.Y', strtotime($a->created_at)); ?>
													</td>
												</tr>
												<?php if($a->updated_at != NULL) : ?>
													<tr>
														<td class="black-text">
															<strong>Geändert am:</strong>
														</td>
														<td class="black-text">
															<?php echo date('d.m.Y', strtotime($a->updated_at)); ?>
														</td>
													</tr>
												<?php endif; ?>
											</table>
										</div>
										<div class="row">
											<div class="col s12 m12 l6">
												<a class="btn waves-effect fullsize light-blue lighten-1 modal-trigger waves-light" href="#editad<?=$a->id;?>">Bearbeiten <i class="material-icons left">edit</i></i></a>
												<div id="editad<?php echo $a->id; ?>" class="modal">
													<div class="modal-content">
														<h4>Bearbeiten von: <strong><?php echo $a->firstname.' '.$a->lastname; ?></strong></h4>
														<div class="row">
															<form action="adminuser/updateadmin/<?=$a->id;?>/adminuser" method="post">
																<div class="input-field col s12 m12 l12 black-text">
																	<input name="firstname" type="text" value="<?=$a->firstname;?>" class="validate" />
																	<label for="firstname">Vorname:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text">
																	<input name="lastname" type="text" value="<?=$a->lastname;?>">
																	<label for="lastname">Nachname:</label>
																</div>
																<div class="input-field col s12 m12 l12 black-text">
																	<input name="email" type="text" value="<?=$a->email;?>">
																	<label for="email">E-Mail:</label>
																</div>
														</div>
													</div>
													<div class="modal-footer">
														<div class="col s12 m12 l6">
															<a class="btn waves-effect fullsize light-blue lighten-1 modal-action modal-close waves-light" href="#!">Schließen <i class="material-icons left">arrow_back</i></a>
														</div>
														<div class="col s12 m12 l6">
															<button class="btn waves-effect waves-light fullsize teal accent-3 black-text" type="submit" id="createDirect" name="action" value="updateadmin">Speichern
																	<i class="material-icons right black-text">done</i>
															</button>
															</form>
														</div>
													</div>
												</div>
											</div>
											<div class="col s12 m12 l6">
												<?php if($loggedadmin->id == $a->id) : ?>
													<a class="btn waves-effect fullsize pink lighten-1 waves-light disabled" href="#">Löschen <i class="material-icons right">delete</i></i></a>
												<?php else : ?>
													<a class="btn waves-effect fullsize pink lighten-1 modal-trigger waves-light" href="#delad<?=$a->id;?>">Löschen <i class="material-icons right">delete</i></i></a>
												<?php endif; ?>
											</div>
										</div>
									</div>
								</div>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
