<div class="section">
    <div class="container">
        <div class="section">
            <div class="l12 s12">
                <h1 class="header center white-text lighten-1 accent-3">Registrierung</h1>
            </div>
        </div>
    </div>
</div>
<div class="divider"></div>
<div class="section">
    <div class="container" id="threeCols">
            <div class="row">
                <div class="col s12 l3 white z-depth-3 colCustom">
                    <div class="icon-block">
                        <h5 class="center light-blue-text">
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                        </h5>
                        <h5 class="center black-text">Smart</h5>

                        <table class="bordered">
                            <tr>
                                <td>
                                    1-3 WebBooks/Monat
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Email-Support
                                </td>
                                <td>
                                    <i class="material-icons">remove_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Telefon-Support
                                </td>
                                <td>
                                    <i class="material-icons">remove_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>Preis / Monat</td>
                                <td>
                                    19,99 €
                                </td>
                            </tr>
                        </table>
                        <p class="center-align">
                            <a class="waves-effect waves-light btn modal-trigger light-blue" href="#modal1">Mehr Infos</a>
                        </p>
                        <div id="modal1" class="modal">
                            <div class="modal-content">
                                <h4>Smart Line</h4>
                                <p>Smart-Line bietet Ihnen die Grundfunktion unseren Services an. Im Rahmen dieses Vertrages haben die die Möglichkei folgenden Leistungen in Anspruch zu nehmen:</p>
                                <table class="striped s12">
                                    <tr>
                                        <td>
                                            Anzahl der WebBooks pro Monat
                                        </td>
                                        <td>
                                            1 bis 3
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Support für die Einbindung des WebBooks in Ihrem Projekt
                                        </td>
                                        <td>
                                            1 Mal
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Vertragslaufzeit
                                        </td>
                                        <td>
                                            12 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Kündigungsfrist
                                        </td>
                                        <td>
                                            3 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Preis / Monat inkl. 19% MwSt.
                                        </td>
                                        <td>
                                            19,99 €
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="modal-footer">
                                <a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat">Schließen</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col s12 l3 offset-l1 white z-depth-3 colCustom">
                    <div class="icon-block">
                        <h5 class="center light-blue-text">
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                        </h5>
                        <h5 class="center black-text">Comfort</h5>

                        <table class="bordered">
                            <tr>
                                <td>
                                    4-10 WebBooks/Monat
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Email-Support
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Telefon-Support
                                </td>
                                <td>
                                    <i class="material-icons">remove_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>Preis / Monat</td>
                                <td>
                                    49,99 €
                                </td>
                            </tr>
                        </table>
                        <p class="center-align">
                            <a class="waves-effect waves-light btn modal-trigger light-blue" href="#modal2">Mehr Infos</a>
                        </p>
                        <div id="modal2" class="modal">
                            <div class="modal-content">
                                <h4>Comfort Line</h4>
                                <p>In der Comfort Line stehen Ihnen folgende Leistungen zur Verfügung:</p>
                                <table class="striped">
                                    <tr>
                                        <td>
                                            Anzahl der WebBooks pro Monat
                                        </td>
                                        <td>
                                            4 bis 10
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Support für die Einbindung des fertigen WebBooks auf Ihrer Webseite
                                        </td>
                                        <td>
                                            2 Mal / Monat
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Email - Support bei Fragen oder Unklarheiten
                                        </td>
                                        <td>
                                            unbegrenzt
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Vertragslaufzeit
                                        </td>
                                        <td>
                                            12 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Kündigungsfrist
                                        </td>
                                        <td>
                                            3 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Preis / Monat inkl. 19% MwSt
                                        </td>
                                        <td>
                                            49,99 €
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="modal-footer">
                                <a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat">Schließen</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col s12 l3 offset-l1 white z-depth-3 colCustom">
                    <div class="icon-block">
                        <h5 class="center light-blue-text">
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                            <i class="material-icons wd25">star_rate</i>
                        </h5>
                        <h5 class="center black-text">Ultimate</h5>

                        <table class="bordered">
                            <tr>
                                <td>
                                    ∞ WebBooks/Monat
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Email-Support
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Telefon-Support
                                </td>
                                <td>
                                    <i class="material-icons">check_circle</i>
                                </td>
                            </tr>
                            <tr>
                                <td>Preis / Monat</td>
                                <td>
                                    89,99 €
                                </td>
                            </tr>
                        </table>
                        <p class="center-align">
                            <a class="waves-effect waves-light btn modal-trigger light-blue" href="#modal3">Mehr Infos</a>
                        </p>
                        <div id="modal3" class="modal">
                            <div class="modal-content">
                                <h4>Ultimate Line</h4>
                                <p>Die Ultimate Line beinhaltet alle Services und Features. In diesem Vertrag haben Sie die besten Konditionen.</p>
                                <table class="striped">
                                    <tr>
                                        <td>
                                            Anzahl der WebBooks pro Monat
                                        </td>
                                        <td>
                                            unbegrenzt
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Support für die Einbindung des fertigen WebBooks auf Ihrer Webseite
                                        </td>
                                        <td>
                                            unbegrenzt
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Email Support bei Fragen oder Unklarheiten
                                        </td>
                                        <td>
                                            unbegrenzt
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Telefonischer Support rund um Ihr WebBook
                                        </td>
                                        <td>
                                            unbegrenzt
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Vertragslaufzeit
                                        </td>
                                        <td>
                                            12 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Kündigungsfrist
                                        </td>
                                        <td>
                                            3 Monate
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Preis / Monat inkl. 19% MwSt.</td>
                                        <td>
                                            89,99 €
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="modal-footer">
                                <a href="#!" class=" modal-action modal-close waves-effect waves-red btn-flat">Schließen</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
<div class="divider"></div>
<div class="section">
    <div class="container">
            <form id="registerForm" name="registerForm" action="/user/createuser" method="post" class="col s12">
                <div class="row">
                    <div class="col l12 s12">
                        <div class="center-align">
                            <h4 class="valign white-text shadowHeader">Bitte geben Sie Ihre vollständigen Daten ein.</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 l12 m12">
                        <select name="tariff" id="tariff">
                            <option value="" disabled selected>Bitte aushwählen</option>
                            <?php foreach ($tariffe as $tariff): ?>
                            <option value="<?=$tariff->id?>"><?=$tariff->title?></option>
                            <?php endforeach; ?>
                        </select>
                        <label for="tariff">Tarif Auswahl: bitte wählen Sie ein Tarif aus.</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l4">
                        <div class="row section inRadioRange">
                            <div class="col l6 s12 m12">
                                <input class="with-gap" name="prefix" type="radio" id="anredeHerr" value="Herr" />
                                <label for="anredeHerr">Herr</label>
                            </div>
                            <div class="col l6 s12 m12">
                                <input class="with-gap" name="prefix" type="radio" id="anredeFrau" value="Frau" />
                                <label for="anredeFrau">Frau</label>
                            </div>
                        </div>
                    </div>
                    <div class="input-field col s12 m12 l4">
                        <i class="mdi-action-account-circle prefix"></i>
                        <input id="first_name" name="firstname" type="text" class="validate" />
                        <label for="first_name">Vorname</label>
                    </div>
                    <div class="input-field col s12 m12 l4">
                        <i class="mdi-action-account-circle prefix"></i>
                        <input id="last_name" name="lastname" type="text" class="validate" />
                        <label for="last_name">Nachname</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">email</i>
                        <input id="email" type="email" name="email" class="validate" />
                        <label for="email">E-Mail</label>
                    </div>
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">lock</i>
                        <input id="password" name="password" type="password" class="validate" />
                        <label for="password">Passwort</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">domain</i>
                        <input id="company" name="company" type="text" />
                        <label for="company">Firma / Organisation</label>
                    </div>
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">phone</i>
                        <input id="phone" name="phone" type="text" />
                        <label for="phone">Telefon</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l8">
                        <i class="material-icons prefix">pin_drop</i>
                        <input name="street" id="street" type="text" class="validate" />
                        <label for="street">Straße</label>
                    </div>
                    <div class="input-field col s12 m12 l4">
                        <i class="material-icons prefix">my_location</i>
                        <input name="zip" id="zip" class="validate" type="text" />
                        <label for="zip">PLZ</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">map</i>
                        <input name="city" id="city" class="validate" type="text" />
                        <label for="city">Stadt</label>
                    </div>
                    <div class="input-field col s12 l6 m12">
                        <select name="land" id="land">
                            <option value="" disabled selected>Bitte aushwählen</option>
                            <?php foreach ($lands as $land): ?>
                            <option value="<?=$land->id?>"><?=$land->title?></option>
                            <?php endforeach; ?>
                        </select>
                        <label for="land">Land Auswahl: bitte wählen Sie ein Land aus.</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l6">
                        <i class="material-icons prefix">edit</i>
                        <input name="steuerid" id="steuerid" type="text" />
                        <label for="steuerid">Steuer-ID</label>
                    </div>
                    <div class="input-field col s12 m12 l6">
                        <input name="agb" id="agb" class="validate" value="agbCh" type="checkbox" />
                        <label for="agb">Bestätige die gültigen AGB</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l6">
                        <a class="btn waves-effect waves-light fullsize light-blue lighten-1" id="clearRegisterForm" name="clearform">
                            Formular leeren
                            <i class="mdi-action-delete right"></i>
                        </a>
                    </div>
                    <div class="input-field col s12 m12 l6">
                        <button class="btn waves-effect waves-light fullsize light-blue lighten-1" type="button" id="checkContent" name="action" value="register">Daten prüfen
                            <i class="mdi-content-send right"></i>
                        </button>

                    </div>
                    <a id="formConfirmTrigger" class="modal-trigger" href="#confirmationData">Data Confirmation</a>
                    <div id="confirmationData" class="modal">
                        <div class="modal-content">
                            <h4>Datenüberprüfung abgeschlossen!</h4>
                            <p>Ihre Daten wurden auf korrekte Eingabe überprüft. Nun können Sie die Registrierung abschließen.</p>
                            <p>Klicken Sie dazu einfach auf den Button <strong>"Registrieren"</strong>.</p>
                        </div>
                        <div class="modal-footer">
                            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Schließen</a>
                        </div>
                    </div>
                    <a id="failedConfirm" class="modal-trigger" href="#confirmationNotOk">Confirmation Failed</a>
                    <div id="confirmationNotOk" class="modal">
                        <div class="modal-content">
                            Hidden Content
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
